<?php

namespace AppBundle\Repository;

/**
 * ConfigurationDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigurationDateRepository extends \Doctrine\ORM\EntityRepository
{
}
