<?php

namespace AppBundle\Repository;

/**
 * InscriptionAutoriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InscriptionAutoriseRepository extends \Doctrine\ORM\EntityRepository
{
}
